# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: notification
services:
  app:
    image: notification
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-postgresql:5432/notification
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://notification-postgresql:5432/notification
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8083/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  rabbitmq:
    extends:
      file: ./rabbitmq.yml
      service: rabbitmq
